### ISSUE TITLE
Вопрос по DXF

### ISSUE THREAD

**Issue by Rost3** [selenur/ToolsGenGkode#1]
в какой версии нужно сохранять  DXF? дело в том что крайне неправильно отображаются некоторые фигуры в програме. или дело в самом содержимом?
![default](https://cloud.githubusercontent.com/assets/24759536/21965863/01f6eeac-db71-11e6-9f0a-d68cf3a30b34.JPG)

**Comment by Rost3** [comment]
несмог загрузить зип архив. вот исходный файл на гугл драйве https://drive.google.com/drive/folders/0ByVgXXm66QJeNk1ib2Jydm5ubk0?usp=sharing

**Comment by selenur** [comment]
Привет!
У меня так-же отображаются, кривовато, постараюсь посмотреть где допустил ошибку. :-)

**Comment by Rost3** [comment]
скачал новую версию 51. таже проблема. круг отображается как квадрат, нет скруглений, выстраивается прямая тежду двумя ближайшими точками, кривые Безье или как их там сторятся тоже фиг знает как. скорее всего вместо построения по формуле,Ваша программа стоит просто по точкам которые используются в уравнении для постоения кривой. поэтому и геометрия улетает в неведомые дали. сохранял в разных версиях через корел Х7 и в  DXF версиях 2009 по последнию возможную для Х7

**Comment by Rost3** [comment]
имеется в виду построение квадратичной и кубичной и прочих кривых по формуле. типа как здесь нарисовано https://ru.wikipedia.org/wiki/Кривая_Безье. я вообще не программист) возможно что дело в формате DXF не того года.

**Comment by selenur** [comment]
В версии 3 исправлена проблема
